# Generated by Django 6.0.5 on 2026-06-03 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_post_tags"),
        ("users", "0002_user_profile_image_user_short_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="like_posts",
            field=models.ManyToManyField(
                blank=True,
                related_name="like_users",
                to="posts.post",
                verbose_name="좋아요 누른 Post목록",
            ),
        ),
        migrations.CreateModel(
            name="Relationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following_relationships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="팔로우를 요청한 사용자",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follower_relationships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="팔로우 요청의 대상",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(
                related_name="followers",
                through="users.Relationship",
                to=settings.AUTH_USER_MODEL,
                verbose_name="팔로우 중인 사용자들",
            ),
        ),
    ]
