# Generated by Django 6.0.5 on 2026-06-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_hashtag_post_tags'),
        ('users', '0003_relationship_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_posts',
            field=models.ManyToManyField(blank=True, related_name='likes_users', to='posts.post', verbose_name='좋아요 누른 Post 목록'),
        ),
    ]
